server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: farhana
    url: jdbc:postgresql://localhost:5433/registration
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect 
        format_sql: true
    show-sql: true